name: Deploy Node.js app to Azure Web App (daniellepcha)

on:
  push:
    branches:
      - backend
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout repo
        uses: actions/checkout@v4

      # 2️⃣ Login to Azure
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_D8F5C3ABE84E4F9FA110708A42208D58 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_F6422F5E20D047F2B4825014904CA0E2 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_77228C5145F249AD9B7DFA36B163DF55 }}

      # 3️⃣ Deploy to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: daniellepcha
          slot-name: Production
          package: .
